name: Allow only dev → main

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate PR source branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Target branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ PR bloqueado"

            # Comenta no PR
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "🚫 **PR fechado automaticamente**  
              Apenas a branch **dev** pode abrir Pull Request para **main**."

            # Fecha o PR
            gh pr close ${{ github.event.pull_request.number }} --comment ""

            exit 1
          fi

          echo "✅ PR permitido: dev → main"
